name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: [ "bug" ]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        
        Rules for reporting a bug:
        -------------------------
        * Make sure the bug hasn't already been reported.
        * Fill in as much of the template below as you're able.
  - type: input
    id: version
    attributes:
      label: Version
      description: What version are you using?
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment that reproduces the issue
      description: What platform are you using (device, OS+version, Browser+version)?
      placeholder: |
        Example:
        * Device: [e.g. iPhone6, Samsung Galaxy S22, macbook pro 2021]
        * OS: [e.g. iOS8.1, Android 11, Windows 10]
        * Browser: [e.g. Chrome 92, Safari 14, Firefox 91]
    validations:
      required: true
  - type: dropdown
    id: reproducible
    attributes:
      label: Is it reproducible in the example application?
      description: Please try and reproduce the issue in the example application.
      options:
        - "Yes"
        - "No"
        - Not tested
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Reproduction steps
      description: Clear and complete steps we can use to reproduce the problem
      placeholder: |
        Example:
        1. Play the attached media in the example application
        2. Seek backward 10s
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected result
      placeholder: |
        Example:
        The media plays successfully
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual result
      placeholder: |
        Example:
        The player crashes with the following stack trace:
        ...
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional context
      placeholder: |
        Example:
        Only reproducible with videoId: vi1234567890
  - type: textarea
    id: logs
    attributes:
      label: Relevant logs output
      description: Please paste any relevant logs output here.
      render: shell
