name: Build Flutter for iOS

on:
  workflow_call:
    inputs:
      cache:
        description: 'Enable caching on Flutter and pub dependencies'
        required: false
        type: boolean
        default: false

jobs:
  build_ios:
    runs-on: macos-14
    defaults:
      run:
        working-directory: example/
    steps:
      - uses: actions/checkout@v4
      - name: Setup Flutter
        id: flutter-action
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: ${{ inputs.cache }}
          cache-key: flutter-:os:-:channel:-:version:-:arch:-:hash:-${{ hashFiles('**/pubspec.yaml') }}
      - name: Build iOS application
        run: flutter build ios --no-codesign
